### ISSUE TITLE
Contribute to OpenJFX

### ISSUE THREAD

**Issue by hh7k8** [codecentric/javafxsvg#12]
Greetings,

Would you be willing to contribute javafxsvg to openjdk.java.net/projects/openjfx ?

If so, and if there is anything I can do to help, please let me know.

Best regards,
Henri

**Comment by 0x4a616e** [comment]
Hi Henri,

in general: yes of course. I guess this would however not include the SVG support itself as this would require apache tiki as a dependency. What could be done is probably creating some "official" interface to plug-in SVG support, but i'm not sure whether something like this is desired for openjfx.

So i guess we'd first need to start a new discussion regarding this interface on the openjfx mailing list.

BR
Jan

**Comment by hh7k8** [comment]
Hi Jan,

Apache tiki?  Apache Batik, perhaps?  I've managed to run the javafxsvg test on the eclipse IDE.  It comes with Batik.

I'll post here when I manage to create a JDK enhancement bug or a mailing list topic. It could be a few days.

Cheers,
Henri

**Comment by 0x4a616e** [comment]
🤦‍♂️ I tried to write tika which was auto corrected tiki, but what I meant was batik of course 😉
