### ISSUE TITLE
NoSuchMethodError with JDK 1.8.0_51

### ISSUE THREAD

**Issue by pdemanget** [codecentric/javafxsvg#4]
I was faced with this bug when using the latest JDK the version is "build 1.8.0_51-b16". Could you accept my pull request that fix it?

**Comment by 0x4a616e** [comment]
Hi, sorry for the delay, but I wasn't really sure how to fix this... Unfortunately fiddling with the private API is always a bit nasty 😕 I now tried to fix this a bit similar to how this is handled internally in the JDK by wrapping this screen resolution stuff into an own helper class. I know it's not perfect, but for me it did the trick. If you have time, you can check out my latest commit: https://github.com/codecentric/javafxsvg/commit/e16685b9d6e0a794dce8cc5b613afff439f6ed5c

**Comment by pdemanget** [comment]
Hello, thank you very much for that fix! 
It works well with my versions of java8 :
1.8.0_51
1.8.0_74
1.8.0_77
1.8.0_92

I know wrapping the private API in a Helper is not very statisfying, but we have no choice, it seem a good solution to me. 
I will use this version in SNAPSHOT, and hope to see a released version on maven repository, or simply a tagged on on github.

**Comment by 0x4a616e** [comment]
Thanks for the confirmation! I added a tag and published a new version `1.2.1` to maven central.
