### ISSUE TITLE
Image width and height will be ignored

### ISSUE THREAD

**Issue by Zerlono** [codecentric/javafxsvg#5]
When you create a image with the width and height parameter set, your SVG-Imageloader will ignore those and pick the default svg-size instead.
new Image("myImage.svg", 100, 100, false, false);
new Image("myImage.svg", 100, 0, true, false);

I debugged a little bit and noticed that BufferedImageTranscoder.setImageSize is called twice. One time with the specified width and height and another time with the default size.
The second time it is called from within SVGAbstractTranscoder.transcode

I really like your SVG support and I'm still using it a lot, but some of my images need to be scaled up first.
Thanks in advanced

**Comment by 0x4a616e** [comment]
Hi, thank you for the report! Can you check the latest commit? https://github.com/codecentric/javafxsvg/commit/31b830c7b165d594c1aeca58c973b030cfd09a44

This should solve the problem!

**Comment by Zerlono** [comment]
Thx, I will try it the next days!

**Comment by Zerlono** [comment]
Worked! This is great thanks
