### ISSUE TITLE
big size

### ISSUE THREAD

**Issue by Zavael** [codecentric/javafxsvg#8]
I used this awesome lib in a 2MB app, but it raised the size to almost 8MB just by using it. Could the size drop in the future or is the "svg support" so resource heavy thing? Thanks

**Comment by 0x4a616e** [comment]
Hi, i doubt that there is anything we can do... The lib basically uses just a single dependency which is apache batik. Unfortunately this single dependency is approx. 8MB in size...  That means there is nothing that can be dropped.

**Comment by Zavael** [comment]
Well, I understand. Too bad for small projects.
